project_id = "pialieyxsjpgaxzytpyn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54326
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://pialieyxsjpgaxzytpyn.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
enable_anonymous_sign_ins = false
enable_signup = true
enable_confirmations = true
secure_password_change = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
template = { invite = "confirmation-email", confirmation = "confirmation-email" }

[auth.sms]
enable_signup = false
enable_confirmations = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.generate-document]
verify_jwt = true

[functions.process-payment]
verify_jwt = true