// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pialieyxsjpgaxzytpyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpYWxpZXl4c2pwZ2F4enl0cHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNDE5NTEsImV4cCI6MjA3MzgxNzk1MX0.z5GSiF-4sJ4GwzC9ohRZbNgbuv9F7RdKuY49hln2-vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});